# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('config.json', '.'),
    ],
    hiddenimports=[
        # Core Python modules that are sometimes missing
        'binascii',
        '_csv',
        'csv',
        'codecs',
        'collections',
        'json',
        'logging',
        'logging.handlers',
        'multiprocessing',
        'multiprocessing.sharedctypes',
        'multiprocessing.heap',
        'multiprocessing.context',
        'multiprocessing.synchronize',
        'multiprocessing.connection',
        'multiprocessing.pool',
        'multiprocessing.queues',
        'multiprocessing.dummy',
        'multiprocessing.managers',
        'multiprocessing.reduction',
        'multiprocessing.spawn',
        'multiprocessing.util',
        'mmap',
        'os',
        'ssl',
        'sys',
        'time',
        'urllib',
        'urllib.parse',
        'uuid',
        'weakref',
        'zipfile',
        'socket',
        'errno',
        'inspect',
        'io',
        'struct',
        'functools',
        'contextlib',
        'threading',
        'queue',
        'datetime',
        'hashlib',
        'base64',
        'html',
        'email',
        'email.mime',
        'email.mime.text',
        'email.mime.multipart',
        'email.utils',
        'importlib',
        'importlib.metadata',
        'importlib.util',
        'importlib.machinery',
        'pkg_resources',
        'platform',
        'tempfile',
        'shutil',
        'pathlib',
        'mimetypes',
        'gzip',
        'zlib',
        'warnings',
        'traceback',
        'copy',
        'decimal',
        'random',
        'secrets',
        'string',
        'textwrap',
        'glob',
        'fnmatch',
        'stat',
        'fileinput',
        'subprocess',
        'signal',
        'array',
        'heapq',
        'bisect',
        'itertools',
        'operator',
        'keyword',
        'reprlib',
        'types',
        'numbers',
        'math',
        'cmath',
        'fractions',
        'statistics',
        
        # AsyncIO and related
        'asyncio',
        'asyncio.events',
        'asyncio.futures',
        'asyncio.locks',
        'asyncio.queues',
        'asyncio.tasks',
        'asyncio.streams',
        'asyncio.exceptions',
        
        # AIOHTTP core modules
        'aiohttp',
        'aiohttp.client',
        'aiohttp.client_exceptions',
        'aiohttp.connector',
        'aiohttp.helpers',
        'aiohttp.http_exceptions',
        'aiohttp.streams',
        'aiohttp.tracing',
        'aiohttp.web',
        'aiohttp.web_exceptions',
        'aiohttp.web_middlewares',
        'aiohttp.web_protocol',
        'aiohttp.web_request',
        'aiohttp.web_response',
        'aiohttp.web_runner',
        'aiohttp.web_server',
        'aiohttp.web_urldispatcher',
        'aiohttp.web_ws',
        'aiohttp.resolver',
        'aiohttp.cookiejar',
        'aiohttp.formdata',
        'aiohttp.multipart',
        'aiohttp.payload',
        'aiohttp.hdrs',
        'aiohttp.abc',
        'aiohttp.typedefs',
        'aiohttp.signals',
        
        # Flask and related
        'flask',
        'flask.json',
        'flask.templating',
        'flask.helpers',
        'flask.wrappers',
        'flask.globals',
        'flask.ctx',
        'flask.config',
        'flask.sessions',
        'flask.logging',
        'flask.signals',
        
        # Jinja2 essentials
        'jinja2',
        'jinja2.compiler',
        'jinja2.environment',
        'jinja2.loaders',
        'jinja2.runtime',
        'jinja2.utils',
        'jinja2.exceptions',
        'jinja2.filters',
        'jinja2.defaults',
        
        # Werkzeug essentials
        'werkzeug',
        'werkzeug.serving',
        'werkzeug.utils',
        'werkzeug.urls',
        'werkzeug.http',
        'werkzeug.datastructures',
        'werkzeug.exceptions',
        'werkzeug.wrappers',
        'werkzeug.routing',
        'werkzeug.wsgi',
        'werkzeug.local',
        
        # Required dependencies
        'multidict',
        'yarl',
        'attrs',
        'charset_normalizer',
        'idna',
        'typing_extensions',
        'async_timeout',
        'aiosignal',
        'frozenlist',
        'click',
        'markupsafe',
        'itsdangerous',
        'blinker',
        'jaraco.text',
        'setuptools._vendor.jaraco.text',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'unittest',
        'test',
        'PIL',
        'matplotlib',
        'numpy',
        'scipy',
        'pandas',
        'sqlite3',
        'pytest',
        'requests',
        'urllib3',
        'cryptography',
        'pywin32',
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='cb_dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
