# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('templates', 'templates'),
        ('static', 'static'),
        ('config.json', '.'),
    ],
    hiddenimports=[
        'aiohttp',
        'aiohttp.client',
        'aiohttp.client_exceptions',
        'aiohttp.connector',
        'aiohttp.helpers',
        'aiohttp.http_exceptions',
        'aiohttp.streams',
        'aiohttp.tracing',
        'aiohttp.web',
        'aiohttp.web_exceptions',
        'aiohttp.web_middlewares',
        'aiohttp.web_protocol',
        'aiohttp.web_request',
        'aiohttp.web_response',
        'aiohttp.web_runner',
        'aiohttp.web_server',
        'aiohttp.web_urldispatcher',
        'aiohttp.web_ws',
        'flask',
        'flask.json',
        'flask.templating',
        'jinja2',
        'asyncio',
        'ssl',
        'logging',
        'logging.handlers',
        'json',
        'os',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='cb_dashboard',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=None,
)
